### ISSUE TITLE
Daemonize script issue — wrong interpreter

### ISSUE THREAD

**Issue by darkhacknet** [nawinds/systemd_services_monitoring#1]
Man this script is the only thing that I need for my bots, its awesome. 

But Im having this issue when trying to run this as a systemd service 

 ene 05 02:01:40 XB-desktop systemd[1]: Started monitoring bot.
ene 05 02:01:40 XB-desktop python3[10678]: Traceback (most recent call last):
ene 05 02:01:40 XB-desktop python3[10678]:   File "/home/xborland/systemd_services_monitoring/bot.py", line 4, in>
ene 05 02:01:40 XB-desktop python3[10678]:     from aiogram import executor
ene 05 02:01:40 XB-desktop python3[10678]: ModuleNotFoundError: No module named 'aiogram'
ene 05 02:01:40 XB-desktop systemd[1]: monitoring.service: Main process exited, code=exited, status=1/FAILURE
ene 05 02:01:40 XB-desktop systemd[1]: monitoring.service: Failed with result 'exit-code'.
ene 05 02:01:40 XB-desktop systemd[1]: monitoring.service: Triggering OnFailure= dependencies.

Would you be so kind to help me ? 
Thanks in advance. 
Regards !

**Comment by nawinds** [comment]
Hello! Nice of you to become interested in my script, thanks a lot!
It seems that aiogram is not installed in your virtual environment. I have made an installation script that works on my OS, which is rather outdated. I apologize I haven't had enough time to make a more detailed documentation.

I recommend you to install all the needed modules manually and handle all errors that appear in your OS. To do that:
```
cd ~/systemd_services_monitoring
ls
```
Check if there is a "venv" directory in a list. If not:
```
python3 -m venv venv
```
After the directory appears, run
```
source venv/bin/activate
pip3 install -r requirements.txt
```
And then try restarting the service. It seems that the installation script did not run properly on your system, but I do not know what were the errors, so I am sorry if my answer is incomplete. Tell me if you a face any errors, I will be glad to help!

**Comment by darkhacknet** [comment]
Hello, 

Thanks a lot for the quick help man. But Im stuck in this and almost sleeping :/ haha

     Active: activating (auto-restart) (Result: exit-code) since Thu 2023-01-05 03:21:16 CST; 4s ago

The script runs perfectly by itself with no daemon but seems to be easy to daemonize but... is not easy at all. 

Have you any idea ?

**Comment by nawinds** [comment]
Sounds weird... do you have the same settings in your service? Working directory should be ~/systemd_services_monitoring and ExecStart ~/systemd_services_monitoring/venv/bin/python3 ~/systemd_services_monitoring/bot.py

Also check the environment variables TOKEN and ADMIN_IDS.

Lastly, you can try changing User and Group in your systemd service config file to the user that succeed in running script directly.
Anyway, the idea is to find out the difference between direct run and the service run

**Comment by darkhacknet** [comment]
Yeah and now is very weird due to the service is running aparently without issues but the bot doesnt respons to the /start and If I run it without daemon works fine. 

Here you have my .service file. 
![Captura de pantalla 2023-01-05 033450](https://user-images.githubusercontent.com/45680149/210748294-becdb06c-ae8d-4007-bee3-82c5ef90f894.png)


could you please tell me if you add something like this on the bot.py file ¡?
#!/home/xxx/venv/bin/python3

**Comment by nawinds** [comment]
No, I haven't added this. But I suggest changing `/usr/bin/python3` to `/home/xborland/systemd_services_monitoring/venv/bin/python3` for you. At least it works fine for me

**Comment by darkhacknet** [comment]
yeeeeeeeee that line was the critical one for me ! Thanks a lot now its working fine ! 

![Captura de pantalla 2023-01-05 033450](https://user-images.githubusercontent.com/45680149/210750544-e1bb0dbd-2b19-4d85-9790-6f1f3e71a947.png)

And also the bot is responding correctly to all the commands ! 

Thanks Mr.

**Comment by nawinds** [comment]
Yoohoo, I am happy to see you have managed to do that! You are always welcome, have a nice day!

**Comment by darkhacknet** [comment]
Thanks for being so kind ! Now your script is helping me a looot !
